# Generated by Django 4.2.3 on 2024-11-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_mobile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], max_length=50),
        ),
    ]
